---
name: Posy-Plugin-Paginate
version: 0.25
author:
  - Kathryn Andersen
abstract: Posy plugin to paginate multiple entries.
license: perl
requires:
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::Paginate:
    file: lib/Posy/Plugin/Paginate.pm
    version: 0.25
generated_by: Module::Build version 0.2611
